### ISSUE TITLE
While looking into a possible mixin issue, I found this

### ISSUE THREAD

**Issue by Sunconure11** [EverlastSino/SinoCate#2]
https://pastebin.com/SMW4pTFn

**Comment by GregTaoo** [comment]
This mixin provides entity generations, i dont exactly know what caused this problem.
It seems to be a mistake of wrong version, of fabric or api ?

**Comment by GregTaoo** [comment]
or even the compatibility among those mods

**Comment by Sunconure11** [comment]
I found the cause and it has been dealt with
